refactor/faq_bot: refactor faq bot
deeppavlov/dialog_flow_demo pull request #3
Opened 2023-02-24 21:11 UTC by kudep

2023-02-25 17:04 UTC, RLKRo requested changes

2023-02-26 11:45 UTC, RLKRo requested changes

2023-02-26 11:45 UTC, RLKRo commented on  frequently_asked_question_bot/README.md
> +In order for the bot to work, set the bot token, example is in [.env](.env.example). First step is setting enviriment variables:
```suggestion
In order for the bot to work, set the bot token, example is in [.env](.env.example). First step is setting environment variables:
```

2023-04-05 08:51 UTC, ruthenian8 approved these changes

2023-04-05 08:51 UTC, ruthenian8 commented on  frequently_asked_question_bot/bot/run.py
> +def get_pipeline(interface_cli=None) -> Pipeline:
```suggestion
def get_pipeline(interface_cli: bool = False) -> Pipeline:
```
Agreed with Roman

2023-04-05 08:51 UTC, ruthenian8 commented on  frequently_asked_question_bot/bot/run.py
> +def get_pipeline(interface_cli=None) -> Pipeline:
We might also want to rename this parameter to use_cli or something else that is more suitable for a boolean variable

2023-04-07 09:47 UTC, merged