Refactor/customer service bot
deeppavlov/dialog_flow_demo pull request #7
Opened 2023-04-07 09:29 UTC by ruthenian8

2023-04-15 19:42 UTC, avsakharov approved these changes

2023-04-18 21:57 UTC, RLKRo requested changes

2023-04-18 21:57 UTC, RLKRo commented on customer_service_bot/bot/run.py
> +from dialog_graph import graph
No such file.

2023-04-18 21:57 UTC, RLKRo commented on customer_service_bot/bot/test.py
> +from dialog_graph.graph import script
No such file.

2023-04-18 21:57 UTC, RLKRo commented on customer_service_bot/README.md
> +docker-compose run bot pytest test.py
No service named `bot`.

2023-04-18 21:57 UTC, RLKRo commented on customer_service_bot/README.md
> +docker-compose run bot python run.py
No service named `bot`.

2023-04-19 07:44 UTC, ruthenian8 commented on customer_service_bot/bot/api/chatgpt.py
> +    """Construct a get_output function encapsulating the execution counter.
Thx

2023-04-19 07:44 UTC, ruthenian8 commented on customer_service_bot/bot/run.py
> +        messenger_interface = None
Thx

2023-04-19 07:44 UTC, ruthenian8 commented on customer_service_bot/bot/test.py
> +from dialog_graph.graph import script
Thx

2023-04-19 07:44 UTC, ruthenian8 commented on customer_service_bot/README.md
> +docker-compose run bot pytest test.py
Thx

2023-04-19 07:45 UTC, ruthenian8 commented on customer_service_bot/README.md
> +docker-compose run bot python run.py
Thx

2023-04-19 17:30 UTC, RLKRo commented
Oh, [the interface_cli issue](https://github.com/deeppavlov/dialog_flow_demo/pull/7#discussion_r1170542838) was introduced in #3 which I didn't notice during its review.
Could you also fix it in [faq_bot](https://github.com/deeppavlov/dialog_flow_demo/blob/main/frequently_asked_question_bot/bot/run.py)?

2023-04-20 12:35 UTC, ruthenian8 commented
> Oh, [the interface_cli issue](https://github.com/deeppavlov/dialog_flow_demo/pull/7#discussion_r1170542838) and the [no such file issue](https://github.com/deeppavlov/dialog_flow_demo/pull/7#discussion_r1170605950) were introduced in #3. Could you also fix them in faq_bot?

Done

2023-04-25 11:37 UTC, RLKRo approved these changes
I fixed some errors in FAQ bot, it now works. I fixed the same errors in customer service bot, but I don't have a token to test it. Could you make sure that customer service bot also works (run tests & run bot)?

2023-05-02 12:03 UTC, kudep approved these changes

2023-05-02 12:03 UTC, merged